version: "3"
services:
  dns:
    image: ghcr.io/0xerr0r/blocky
    # container_name: blocky1
    restart: unless-stopped
    # ports:
    #   - "127.0.0.1:5342:53/tcp"
    #   - "127.0.0.1:5342:53/udp"
    #   - "4000:4000/tcp"
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./config.yml:/app/config.yml
    depends_on:
      - redis
#     healthcheck:
#       disable: true
