version: "3"
name: blocky
services:
  dns1:
    extends:
      file: common.yml
      service: dns
    
  dns2:
    extends:
      file: common.yml
      service: dns

  dns3:
    extends:
      file: common.yml
      service: dns

  redis:
    image: redis:alpine
    environment:
      - TZ=Asia/Bangkok
    restart: always
    volumes:
      - redis:/data

  nginx:
    image: nginx:alpine
#     container_name: blocky_balancer
    restart: unless-stopped
    # network_mode: host
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Asia/Bangkok

volumes:
  redis:
