version: "3"
name: blocky
services:
  dns1:
    extends:
      file: common.yml
      service: dns
#     container_name: blocky1
    
  dns2:
    extends:
      file: common.yml
      service: dns
#     container_name: blocky2

  dns3:
    extends:
      file: common.yml
      service: dns
#     container_name: blocky3

  redis:
    image: redis:alpine
#     container_name: blocky_redis
    environment:
      - TZ=Asia/Bangkok
    restart: always
    volumes:
      - redis:/data

  nginx:
    image: nginx:alpine
#     container_name: blocky_balancer
    restart: unless-stopped
    # network_mode: host
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Asia/Bangkok
    depends_on:
      - dns1
      - dns2
      - dns3

volumes:
  redis:
